name: OGM Duyurular Scraper

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu çek
      uses: actions/checkout@v3

    - name: Node.js kur
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Bağımlılıkları kur
      run: npm install

    - name: Chromium'u indir (Puppeteer için)
      run: npx puppeteer browsers install chrome

    - name: Scraper scriptini çalıştır
      run: node duyurular.js


    - name: Değişiklikleri commit et ve pushla
      run: |
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git add duyurular.json
         git commit -m "Otomatik güncel duyurular json" || echo "No changes to commit"
         git push
